import type { AppSettings } from "@/types/domain";

export const defaultSettings: AppSettings = {
  profile: {
    id: "",
    displayName: "",
    timeZone: "UTC",
    schoolYear: "",
    weekStart: "monday",
    theme: "system",
  },
  study: {
    earliestTime: "07:00",
    latestTime: "22:00",
    preferredSessionMinutes: 45,
    maxSessionMinutes: 90,
    breakMinutes: 10,
    weekdayWorkloadMinutes: 120,
    weekendWorkloadMinutes: 180,
    minimumFreeMinutes: 30,
    emergencyBufferMinutes: 30,
    studyBeforeSchool: false,
    studyAtLunch: false,
    studyAfterRowing: false,
    fridayNight: "normal",
    saturdayNight: "normal",
    sundayNight: "normal",
  },
  sleep: {
    currentBedtime: "23:00",
    targetBedtime: "23:00",
    wakeTime: "07:00",
    gradualAdjustment: false,
    protectSleep: true,
    preventLateStudy: true,
    athleteRecoveryMode: false,
    avoidIntenseAfterTraining: false,
  },
  subjects: [],
  calendar: {
    studyCalendar: "",
    busyCalendars: [],
    automaticPublishing: false,
    previewBeforePublishing: true,
    notifications: true,
    canvaiMayMoveOwnEvents: false,
    preserveManualEdits: true,
  },
  ai: {
    enabled: false,
    provider: "",
    analysisDepth: "balanced",
    showReasoning: true,
    automaticDuration: false,
    automaticClassification: false,
    useCompletionHistory: false,
    askBeforeMajorChanges: true,
    estimateFeedback: false,
  },
  rules: {
    testsExtraPriority: true,
    startEssaysEarly: true,
    splitLongAssignments: true,
    createProjectMilestones: true,
    missingOverrides: true,
    delayLowValueWhenOverloaded: true,
    allowSameCourseSessions: false,
    includePrepInstructions: true,
    rebuildMissedSchedules: true,
    keepSundayLight: false,
    protectDailyFreeTime: true,
  },
};
