import type {
  AppSettings,
  Assignment,
  Course,
  DemoBootstrap,
  InsightMetric,
  Notification,
  RoutineBlock,
  StudySession,
  WeeklyWorkload,
} from "@/types/domain";
import { DEMO_REFERENCE_DATE, demoDate } from "@/lib/demo-date";

export const courses: Course[] = [
  { id: "course-seminar", name: "AP Seminar", shortName: "Seminar", color: "var(--c-seminar)" },
  { id: "course-english", name: "English", shortName: "English", color: "var(--c-english)" },
  { id: "course-precalc", name: "Precalculus", shortName: "Precalc", color: "var(--c-precalc)" },
  { id: "course-physics", name: "Physics", shortName: "Physics", color: "var(--c-physics)" },
  { id: "course-business", name: "Business", shortName: "Business", color: "var(--c-business)" },
  { id: "course-history", name: "World History", shortName: "History", color: "var(--c-history)" },
];

export const studySessions: StudySession[] = [
  {
    id: "session-seminar-1",
    assignmentId: "assignment-seminar",
    title: "AP Seminar — draft",
    startAt: demoDate(0, "20:30"),
    durationMinutes: 45,
    status: "planned",
    source: "canvai",
  },
  {
    id: "session-physics-1",
    assignmentId: "assignment-physics",
    title: "Physics — test prep",
    startAt: demoDate(0, "21:25"),
    durationMinutes: 45,
    status: "planned",
    source: "canvai",
  },
  {
    id: "session-essay-1",
    assignmentId: "assignment-english",
    title: "English — outline",
    startAt: demoDate(1, "20:15"),
    durationMinutes: 40,
    status: "planned",
    source: "canvai",
  },
  {
    id: "session-business-1",
    assignmentId: "assignment-business",
    title: "Business — slides",
    startAt: demoDate(3, "11:00"),
    durationMinutes: 60,
    status: "rescheduled",
    source: "canvai",
  },
];

export const assignments: Assignment[] = [
  {
    id: "assignment-seminar",
    courseId: "course-seminar",
    title: "Source analysis research draft",
    description: "Synthesize three sources into a defensible research position and cite evidence.",
    type: "essay",
    dueAt: demoDate(1),
    points: 100,
    gradeWeight: 12,
    estimatedMinutes: 135,
    priority: "high",
    submissionStatus: "in_progress",
    missing: false,
    completionState: "open",
    scheduledSessionIds: ["session-seminar-1"],
    canvasUrl: "https://canvas.example.test/assignments/seminar",
    analysis: {
      difficulty: 5,
      urgency: 5,
      priorityScore: 89,
      explanation:
        "Writing-heavy and due first. Starting while energy is high lowers the risk of a late draft.",
      suggestedSteps: [
        "Confirm the claim and source roles",
        "Draft two evidence paragraphs",
        "Add citations and revise the conclusion",
      ],
    },
  },
  {
    id: "assignment-english",
    courseId: "course-english",
    title: "The Great Gatsby literary essay",
    description:
      "Write a five-page analysis of how setting reinforces the novel’s central conflict.",
    type: "essay",
    dueAt: demoDate(3),
    points: 120,
    gradeWeight: 15,
    estimatedMinutes: 210,
    priority: "high",
    submissionStatus: "not_started",
    missing: false,
    completionState: "open",
    scheduledSessionIds: ["session-essay-1"],
    canvasUrl: "https://canvas.example.test/assignments/english",
    analysis: {
      difficulty: 5,
      urgency: 4,
      priorityScore: 84,
      explanation:
        "The essay is not due first, but its length makes an early outline the safest move.",
      suggestedSteps: [
        "Choose a thesis",
        "Collect three quotations",
        "Draft the outline",
        "Write and revise in separate sessions",
      ],
    },
  },
  {
    id: "assignment-precalc",
    courseId: "course-precalc",
    title: "Worksheet 5.2",
    description: "Complete problems 1–24 on inverse functions and show all work.",
    type: "homework",
    dueAt: demoDate(1, "08:00"),
    points: 25,
    estimatedMinutes: 30,
    actualMinutes: 18,
    priority: "medium",
    submissionStatus: "in_progress",
    missing: false,
    completionState: "open",
    scheduledSessionIds: [],
    canvasUrl: "https://canvas.example.test/assignments/precalc",
    analysis: {
      difficulty: 3,
      urgency: 4,
      priorityScore: 68,
      explanation:
        "Short and already mostly complete; finishing at lunch avoids using evening focus time.",
      suggestedSteps: ["Finish problems 17–24", "Check odd answers", "Upload before first period"],
    },
  },
  {
    id: "assignment-physics",
    courseId: "course-physics",
    title: "Kinematics unit test",
    description:
      "Prepare for the kinematics unit test covering graphs, vectors, and projectile motion.",
    type: "test",
    dueAt: demoDate(2, "10:15"),
    points: 150,
    gradeWeight: 18,
    estimatedMinutes: 150,
    priority: "urgent",
    submissionStatus: "not_started",
    missing: false,
    completionState: "open",
    scheduledSessionIds: ["session-physics-1"],
    canvasUrl: "https://canvas.example.test/assignments/physics",
    analysis: {
      difficulty: 5,
      urgency: 5,
      priorityScore: 92,
      explanation:
        "This is the highest-weight assessment and benefits from two shorter sessions instead of one cram block.",
      suggestedSteps: [
        "Review motion graphs",
        "Work six mixed problems",
        "Make an error log",
        "Do a short recall review Thursday morning",
      ],
    },
  },
  {
    id: "assignment-business",
    courseId: "course-business",
    title: "Market analysis presentation",
    description: "Create a six-slide competitor analysis and prepare a four-minute presentation.",
    type: "presentation",
    dueAt: demoDate(5, "09:00"),
    points: 80,
    gradeWeight: 10,
    estimatedMinutes: 180,
    priority: "medium",
    submissionStatus: "not_started",
    missing: false,
    completionState: "open",
    scheduledSessionIds: ["session-business-1"],
    canvasUrl: "https://canvas.example.test/assignments/business",
    analysis: {
      difficulty: 3,
      urgency: 2,
      priorityScore: 57,
      explanation:
        "There is enough runway, but creating the slide skeleton now will prevent a Sunday pileup.",
      suggestedSteps: [
        "Select competitors",
        "Build slide skeleton",
        "Add evidence",
        "Rehearse twice",
      ],
    },
  },
  {
    id: "assignment-history",
    courseId: "course-history",
    title: "Industrial Revolution reading",
    description: "Read pages 184–211 and answer the document questions.",
    type: "reading",
    dueAt: demoDate(4),
    points: 20,
    estimatedMinutes: 55,
    actualMinutes: 48,
    priority: "low",
    submissionStatus: "submitted",
    missing: false,
    completionState: "completed",
    scheduledSessionIds: [],
    canvasUrl: "https://canvas.example.test/assignments/history",
    analysis: {
      difficulty: 2,
      urgency: 1,
      priorityScore: 24,
      explanation: "Completed ahead of the deadline; no additional planning is needed.",
      suggestedSteps: [],
    },
  },
  {
    id: "assignment-missing",
    courseId: "course-history",
    title: "Primary source reflection",
    description: "Submit the short response comparing two factory-worker accounts.",
    type: "reading",
    dueAt: demoDate(-2),
    points: 15,
    estimatedMinutes: 25,
    priority: "urgent",
    submissionStatus: "not_started",
    missing: true,
    completionState: "open",
    scheduledSessionIds: [],
    canvasUrl: "https://canvas.example.test/assignments/missing",
    analysis: {
      difficulty: 2,
      urgency: 5,
      priorityScore: 95,
      explanation:
        "Canvas reports this as missing. A short recovery block should happen before new low-value work.",
      suggestedSteps: [
        "Re-open the source excerpts",
        "Write the 250-word comparison",
        "Submit and confirm the receipt",
      ],
    },
  },
];

export const routineBlocks: RoutineBlock[] = [
  {
    id: "routine-tue-commute-am",
    day: "Tuesday",
    activity: "Commute",
    startTime: "07:25",
    endTime: "08:30",
    color: "gray",
  },
  {
    id: "routine-tue-school",
    day: "Tuesday",
    activity: "School",
    startTime: "08:30",
    endTime: "15:30",
    color: "gray",
  },
  {
    id: "routine-tue-commute-pm",
    day: "Tuesday",
    activity: "Commute",
    startTime: "15:30",
    endTime: "16:30",
    color: "gray",
  },
  {
    id: "routine-tue-rowing",
    day: "Tuesday",
    activity: "Rowing",
    startTime: "16:30",
    endTime: "19:00",
    color: "green",
  },
  {
    id: "routine-tue-commute-evening",
    day: "Tuesday",
    activity: "Commute",
    startTime: "19:30",
    endTime: "19:45",
    color: "gray",
  },
  {
    id: "routine-tue-dinner",
    day: "Tuesday",
    activity: "Dinner",
    startTime: "20:00",
    endTime: "20:30",
    color: "amber",
  },
  {
    id: "routine-mon-school",
    day: "Monday",
    activity: "School",
    startTime: "08:30",
    endTime: "15:30",
    color: "gray",
  },
  {
    id: "routine-wed-rowing",
    day: "Wednesday",
    activity: "Rowing",
    startTime: "16:30",
    endTime: "19:00",
    color: "green",
  },
  {
    id: "routine-thu-rowing",
    day: "Thursday",
    activity: "Rowing",
    startTime: "16:30",
    endTime: "19:00",
    color: "green",
  },
  {
    id: "routine-sat-lifting",
    day: "Saturday",
    activity: "Lifting",
    startTime: "10:00",
    endTime: "11:00",
    color: "accent",
  },
];

export const notifications: Notification[] = [
  {
    id: "notif-new",
    kind: "new",
    title: "New Canvas assignment",
    body: "Business — Market analysis presentation was imported.",
    timeLabel: "12m",
    read: false,
  },
  {
    id: "notif-date",
    kind: "changed",
    title: "Due date changed",
    body: "English essay moved to Friday at 11:59 PM.",
    timeLabel: "1h",
    read: false,
  },
  {
    id: "notif-moved",
    kind: "moved",
    title: "Study session moved",
    body: "Physics prep shifted to 9:25 PM after practice.",
    timeLabel: "2h",
    read: false,
  },
  {
    id: "notif-missing",
    kind: "missing",
    title: "Missing work detected",
    body: "World History reflection is past its due date.",
    timeLabel: "5h",
    read: false,
  },
  {
    id: "notif-resolved",
    kind: "resolved",
    title: "Conflict resolved",
    body: "Dinner and the AP Seminar draft no longer overlap.",
    timeLabel: "8h",
    read: true,
  },
  {
    id: "notif-calendar",
    kind: "connection",
    title: "Google Calendar",
    body: "Demo mode is active; no events will be published.",
    timeLabel: "1d",
    read: true,
  },
];

export const weeklyWorkload: WeeklyWorkload[] = [
  {
    date: demoDate(-2),
    day: "Mon",
    plannedMinutes: 90,
    capacityMinutes: 150,
    deadlinePressure: 35,
    tests: 0,
    writingHeavy: false,
  },
  {
    date: demoDate(-1),
    day: "Tue",
    plannedMinutes: 60,
    capacityMinutes: 120,
    deadlinePressure: 42,
    tests: 0,
    writingHeavy: false,
  },
  {
    date: demoDate(0),
    day: "Wed",
    plannedMinutes: 120,
    capacityMinutes: 150,
    deadlinePressure: 74,
    tests: 0,
    writingHeavy: true,
  },
  {
    date: demoDate(1),
    day: "Thu",
    plannedMinutes: 150,
    capacityMinutes: 160,
    deadlinePressure: 92,
    tests: 1,
    writingHeavy: true,
  },
  {
    date: demoDate(2),
    day: "Fri",
    plannedMinutes: 30,
    capacityMinutes: 120,
    deadlinePressure: 66,
    tests: 1,
    writingHeavy: true,
  },
  {
    date: demoDate(3),
    day: "Sat",
    plannedMinutes: 60,
    capacityMinutes: 180,
    deadlinePressure: 38,
    tests: 0,
    writingHeavy: false,
  },
  {
    date: demoDate(4),
    day: "Sun",
    plannedMinutes: 180,
    capacityMinutes: 135,
    deadlinePressure: 88,
    tests: 0,
    writingHeavy: true,
  },
];

export const defaultSettings: AppSettings = {
  profile: {
    id: "user-demo",
    displayName: "Maya Kessler",
    timeZone: "America/Los_Angeles",
    schoolYear: "Junior",
    weekStart: "monday",
    theme: "light",
  },
  study: {
    earliestTime: "06:45",
    latestTime: "22:15",
    preferredSessionMinutes: 45,
    maxSessionMinutes: 75,
    breakMinutes: 10,
    weekdayWorkloadMinutes: 150,
    weekendWorkloadMinutes: 180,
    minimumFreeMinutes: 60,
    emergencyBufferMinutes: 30,
    studyBeforeSchool: false,
    studyAtLunch: true,
    studyAfterRowing: true,
    fridayNight: "light",
    saturdayNight: "avoid",
    sundayNight: "light",
  },
  sleep: {
    currentBedtime: "23:00",
    targetBedtime: "22:30",
    wakeTime: "06:30",
    gradualAdjustment: true,
    protectSleep: true,
    preventLateStudy: true,
    athleteRecoveryMode: true,
    avoidIntenseAfterTraining: true,
  },
  subjects: courses.map((course) => ({
    courseId: course.id,
    difficulty: ["course-seminar", "course-english"].includes(course.id)
      ? 5
      : course.id === "course-physics"
        ? 4
        : 3,
    confidence: course.id === "course-physics" ? 3 : 4,
    importance: 4,
    typicalMinutes: ["course-seminar", "course-english"].includes(course.id) ? 90 : 50,
    testDifficulty: course.id === "course-physics" ? 5 : 3,
    extraTimeMultiplier: ["course-seminar", "course-english"].includes(course.id) ? 1.4 : 1.1,
  })),
  calendar: {
    studyCalendar: "Canvas Sweeper Study",
    busyCalendars: ["School", "Rowing", "Family"],
    automaticPublishing: false,
    previewBeforePublishing: true,
    notifications: true,
    canvaiMayMoveOwnEvents: true,
    preserveManualEdits: true,
  },
  ai: {
    enabled: true,
    provider: "Demo provider",
    analysisDepth: "balanced",
    showReasoning: true,
    automaticDuration: true,
    automaticClassification: true,
    useCompletionHistory: true,
    askBeforeMajorChanges: true,
    estimateFeedback: true,
  },
  rules: {
    testsExtraPriority: true,
    startEssaysEarly: true,
    splitLongAssignments: true,
    createProjectMilestones: true,
    missingOverrides: true,
    delayLowValueWhenOverloaded: true,
    allowSameCourseSessions: false,
    includePrepInstructions: true,
    rebuildMissedSchedules: true,
    keepSundayLight: true,
    protectDailyFreeTime: true,
  },
};

export const insightMetrics: InsightMetric[] = [
  {
    id: "early",
    label: "Completed before deadline",
    value: "82%",
    change: "+9% this month",
    explanation: "Work is increasingly finishing before the final evening.",
    adjustment: "Canvai will keep starting essays two days earlier.",
  },
  {
    id: "missed",
    label: "Missed study sessions",
    value: "2",
    change: "of 18 planned",
    explanation: "Both misses followed late rowing practices.",
    adjustment: "Canvai may leave a 20-minute recovery buffer after training.",
  },
  {
    id: "consistency",
    label: "Weekly consistency",
    value: "86%",
    change: "+6 points",
    explanation: "Short weekday sessions are being completed more reliably.",
    adjustment: "Canvai will favor 45-minute blocks over 75-minute blocks.",
  },
  {
    id: "sleep",
    label: "Sleep protected",
    value: "6/7",
    change: "nights this week",
    explanation: "One session ran 20 minutes past the study cutoff.",
    adjustment: "Canvai will stop adding intense work after 10:15 PM.",
  },
];

export const demoBootstrap: DemoBootstrap = {
  referenceDate: DEMO_REFERENCE_DATE,
  courses,
  assignments,
  sessions: studySessions,
  routine: routineBlocks,
  notifications,
  workload: weeklyWorkload,
  settings: defaultSettings,
  canvasConnection: {
    provider: "canvas",
    status: "demo",
    lastSync: "2 minutes ago",
    permissions: ["Read assignments", "Read submission status"],
  },
  calendarConnection: {
    provider: "google-calendar",
    status: "not_connected",
    permissions: ["Read busy times", "Create study events"],
  },
};
